# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dreambot/CombinedPathStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dreambot.msg

class CombinedPathStatus(genpy.Message):
  _md5sum = "5fe88b32f7d29dd3ec2430f387f8a6ea"
  _type = "dreambot/CombinedPathStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """dreambot/PathArray path
bool node_active
bool path_published

================================================================================
MSG: dreambot/PathArray
float64[] x
float64[] y
"""
  __slots__ = ['path','node_active','path_published']
  _slot_types = ['dreambot/PathArray','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       path,node_active,path_published

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CombinedPathStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.path is None:
        self.path = dreambot.msg.PathArray()
      if self.node_active is None:
        self.node_active = False
      if self.path_published is None:
        self.path_published = False
    else:
      self.path = dreambot.msg.PathArray()
      self.node_active = False
      self.path_published = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.path.x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.path.x))
      length = len(self.path.y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.path.y))
      _x = self
      buff.write(_get_struct_2B().pack(_x.node_active, _x.path_published))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.path is None:
        self.path = dreambot.msg.PathArray()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path.x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path.y = s.unpack(str[start:end])
      _x = self
      start = end
      end += 2
      (_x.node_active, _x.path_published,) = _get_struct_2B().unpack(str[start:end])
      self.node_active = bool(self.node_active)
      self.path_published = bool(self.path_published)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.path.x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.path.x.tostring())
      length = len(self.path.y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.path.y.tostring())
      _x = self
      buff.write(_get_struct_2B().pack(_x.node_active, _x.path_published))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.path is None:
        self.path = dreambot.msg.PathArray()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path.x = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.path.y = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 2
      (_x.node_active, _x.path_published,) = _get_struct_2B().unpack(str[start:end])
      self.node_active = bool(self.node_active)
      self.path_published = bool(self.path_published)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
