// Generated by gencpp from file dreambot_tkinter/BoolString.msg
// DO NOT EDIT!


#ifndef DREAMBOT_TKINTER_MESSAGE_BOOLSTRING_H
#define DREAMBOT_TKINTER_MESSAGE_BOOLSTRING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dreambot_tkinter
{
template <class ContainerAllocator>
struct BoolString_
{
  typedef BoolString_<ContainerAllocator> Type;

  BoolString_()
    : flag(false)
    , data()  {
    }
  BoolString_(const ContainerAllocator& _alloc)
    : flag(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::dreambot_tkinter::BoolString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dreambot_tkinter::BoolString_<ContainerAllocator> const> ConstPtr;

}; // struct BoolString_

typedef ::dreambot_tkinter::BoolString_<std::allocator<void> > BoolString;

typedef boost::shared_ptr< ::dreambot_tkinter::BoolString > BoolStringPtr;
typedef boost::shared_ptr< ::dreambot_tkinter::BoolString const> BoolStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dreambot_tkinter::BoolString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dreambot_tkinter::BoolString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dreambot_tkinter::BoolString_<ContainerAllocator1> & lhs, const ::dreambot_tkinter::BoolString_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dreambot_tkinter::BoolString_<ContainerAllocator1> & lhs, const ::dreambot_tkinter::BoolString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dreambot_tkinter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dreambot_tkinter::BoolString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot_tkinter::BoolString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot_tkinter::BoolString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "887125dffa34591677d9e1a87628fc0c";
  }

  static const char* value(const ::dreambot_tkinter::BoolString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x887125dffa345916ULL;
  static const uint64_t static_value2 = 0x77d9e1a87628fc0cULL;
};

template<class ContainerAllocator>
struct DataType< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dreambot_tkinter/BoolString";
  }

  static const char* value(const ::dreambot_tkinter::BoolString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
"string data\n"
;
  }

  static const char* value(const ::dreambot_tkinter::BoolString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dreambot_tkinter::BoolString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dreambot_tkinter::BoolString_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREAMBOT_TKINTER_MESSAGE_BOOLSTRING_H
