// Generated by gencpp from file dreambot_tkinter/BoolInt.msg
// DO NOT EDIT!


#ifndef DREAMBOT_TKINTER_MESSAGE_BOOLINT_H
#define DREAMBOT_TKINTER_MESSAGE_BOOLINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dreambot_tkinter
{
template <class ContainerAllocator>
struct BoolInt_
{
  typedef BoolInt_<ContainerAllocator> Type;

  BoolInt_()
    : flag(false)
    , number(0)  {
    }
  BoolInt_(const ContainerAllocator& _alloc)
    : flag(false)
    , number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::dreambot_tkinter::BoolInt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dreambot_tkinter::BoolInt_<ContainerAllocator> const> ConstPtr;

}; // struct BoolInt_

typedef ::dreambot_tkinter::BoolInt_<std::allocator<void> > BoolInt;

typedef boost::shared_ptr< ::dreambot_tkinter::BoolInt > BoolIntPtr;
typedef boost::shared_ptr< ::dreambot_tkinter::BoolInt const> BoolIntConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dreambot_tkinter::BoolInt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dreambot_tkinter::BoolInt_<ContainerAllocator1> & lhs, const ::dreambot_tkinter::BoolInt_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag &&
    lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dreambot_tkinter::BoolInt_<ContainerAllocator1> & lhs, const ::dreambot_tkinter::BoolInt_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dreambot_tkinter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dreambot_tkinter::BoolInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot_tkinter::BoolInt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot_tkinter::BoolInt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8892900a4cac102c481821cbfef5b68";
  }

  static const char* value(const ::dreambot_tkinter::BoolInt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8892900a4cac102ULL;
  static const uint64_t static_value2 = 0xc481821cbfef5b68ULL;
};

template<class ContainerAllocator>
struct DataType< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dreambot_tkinter/BoolInt";
  }

  static const char* value(const ::dreambot_tkinter::BoolInt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
"int32 number\n"
;
  }

  static const char* value(const ::dreambot_tkinter::BoolInt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolInt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dreambot_tkinter::BoolInt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dreambot_tkinter::BoolInt_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREAMBOT_TKINTER_MESSAGE_BOOLINT_H
