// Generated by gencpp from file dreambot/TargetVelocityResult.msg
// DO NOT EDIT!


#ifndef DREAMBOT_MESSAGE_TARGETVELOCITYRESULT_H
#define DREAMBOT_MESSAGE_TARGETVELOCITYRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dreambot
{
template <class ContainerAllocator>
struct TargetVelocityResult_
{
  typedef TargetVelocityResult_<ContainerAllocator> Type;

  TargetVelocityResult_()
    {
    }
  TargetVelocityResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::dreambot::TargetVelocityResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dreambot::TargetVelocityResult_<ContainerAllocator> const> ConstPtr;

}; // struct TargetVelocityResult_

typedef ::dreambot::TargetVelocityResult_<std::allocator<void> > TargetVelocityResult;

typedef boost::shared_ptr< ::dreambot::TargetVelocityResult > TargetVelocityResultPtr;
typedef boost::shared_ptr< ::dreambot::TargetVelocityResult const> TargetVelocityResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dreambot::TargetVelocityResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dreambot::TargetVelocityResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace dreambot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dreambot::TargetVelocityResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dreambot::TargetVelocityResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dreambot::TargetVelocityResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dreambot::TargetVelocityResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dreambot/TargetVelocityResult";
  }

  static const char* value(const ::dreambot::TargetVelocityResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
;
  }

  static const char* value(const ::dreambot::TargetVelocityResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetVelocityResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dreambot::TargetVelocityResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::dreambot::TargetVelocityResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DREAMBOT_MESSAGE_TARGETVELOCITYRESULT_H
