; Auto-generated. Do not edit!


(cl:in-package dreambot-msg)


;//! \htmlinclude ReachGoalFeedback.msg.html

(cl:defclass <ReachGoalFeedback> (roslisp-msg-protocol:ros-message)
  ((distance_to_goal
    :reader distance_to_goal
    :initarg :distance_to_goal
    :type cl:float
    :initform 0.0))
)

(cl:defclass ReachGoalFeedback (<ReachGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReachGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReachGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dreambot-msg:<ReachGoalFeedback> is deprecated: use dreambot-msg:ReachGoalFeedback instead.")))

(cl:ensure-generic-function 'distance_to_goal-val :lambda-list '(m))
(cl:defmethod distance_to_goal-val ((m <ReachGoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dreambot-msg:distance_to_goal-val is deprecated.  Use dreambot-msg:distance_to_goal instead.")
  (distance_to_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReachGoalFeedback>) ostream)
  "Serializes a message object of type '<ReachGoalFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'distance_to_goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReachGoalFeedback>) istream)
  "Deserializes a message object of type '<ReachGoalFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance_to_goal) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReachGoalFeedback>)))
  "Returns string type for a message object of type '<ReachGoalFeedback>"
  "dreambot/ReachGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReachGoalFeedback)))
  "Returns string type for a message object of type 'ReachGoalFeedback"
  "dreambot/ReachGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReachGoalFeedback>)))
  "Returns md5sum for a message object of type '<ReachGoalFeedback>"
  "6ad47d3db7202cba81252eaa6fcd95a5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReachGoalFeedback)))
  "Returns md5sum for a message object of type 'ReachGoalFeedback"
  "6ad47d3db7202cba81252eaa6fcd95a5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReachGoalFeedback>)))
  "Returns full string definition for message of type '<ReachGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 distance_to_goal  # Feedback - current distance to the goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReachGoalFeedback)))
  "Returns full string definition for message of type 'ReachGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 distance_to_goal  # Feedback - current distance to the goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReachGoalFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReachGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ReachGoalFeedback
    (cl:cons ':distance_to_goal (distance_to_goal msg))
))
