; Auto-generated. Do not edit!


(cl:in-package dreambot-msg)


;//! \htmlinclude TargetVelocityFeedback.msg.html

(cl:defclass <TargetVelocityFeedback> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TargetVelocityFeedback (<TargetVelocityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TargetVelocityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TargetVelocityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dreambot-msg:<TargetVelocityFeedback> is deprecated: use dreambot-msg:TargetVelocityFeedback instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <TargetVelocityFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dreambot-msg:success-val is deprecated.  Use dreambot-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TargetVelocityFeedback>) ostream)
  "Serializes a message object of type '<TargetVelocityFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TargetVelocityFeedback>) istream)
  "Deserializes a message object of type '<TargetVelocityFeedback>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TargetVelocityFeedback>)))
  "Returns string type for a message object of type '<TargetVelocityFeedback>"
  "dreambot/TargetVelocityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TargetVelocityFeedback)))
  "Returns string type for a message object of type 'TargetVelocityFeedback"
  "dreambot/TargetVelocityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TargetVelocityFeedback>)))
  "Returns md5sum for a message object of type '<TargetVelocityFeedback>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TargetVelocityFeedback)))
  "Returns md5sum for a message object of type 'TargetVelocityFeedback"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TargetVelocityFeedback>)))
  "Returns full string definition for message of type '<TargetVelocityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success  # Result: indicates if the action was successful~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TargetVelocityFeedback)))
  "Returns full string definition for message of type 'TargetVelocityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success  # Result: indicates if the action was successful~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TargetVelocityFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TargetVelocityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TargetVelocityFeedback
    (cl:cons ':success (success msg))
))
