; Auto-generated. Do not edit!


(cl:in-package dreambot-msg)


;//! \htmlinclude TargetVelocityGoal.msg.html

(cl:defclass <TargetVelocityGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TargetVelocityGoal (<TargetVelocityGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TargetVelocityGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TargetVelocityGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dreambot-msg:<TargetVelocityGoal> is deprecated: use dreambot-msg:TargetVelocityGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TargetVelocityGoal>) ostream)
  "Serializes a message object of type '<TargetVelocityGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TargetVelocityGoal>) istream)
  "Deserializes a message object of type '<TargetVelocityGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TargetVelocityGoal>)))
  "Returns string type for a message object of type '<TargetVelocityGoal>"
  "dreambot/TargetVelocityGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TargetVelocityGoal)))
  "Returns string type for a message object of type 'TargetVelocityGoal"
  "dreambot/TargetVelocityGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TargetVelocityGoal>)))
  "Returns md5sum for a message object of type '<TargetVelocityGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TargetVelocityGoal)))
  "Returns md5sum for a message object of type 'TargetVelocityGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TargetVelocityGoal>)))
  "Returns full string definition for message of type '<TargetVelocityGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# TargetVelocity.action~%~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TargetVelocityGoal)))
  "Returns full string definition for message of type 'TargetVelocityGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# TargetVelocity.action~%~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TargetVelocityGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TargetVelocityGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TargetVelocityGoal
))
