// Generated by gencpp from file dreambot_examples/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DREAMBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H
#define DREAMBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <dreambot_examples/AddTwoIntsRequest.h>
#include <dreambot_examples/AddTwoIntsResponse.h>


namespace dreambot_examples
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace dreambot_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dreambot_examples::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::dreambot_examples::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::dreambot_examples::AddTwoInts > {
  static const char* value()
  {
    return "dreambot_examples/AddTwoInts";
  }

  static const char* value(const ::dreambot_examples::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::dreambot_examples::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::dreambot_examples::AddTwoInts >
template<>
struct MD5Sum< ::dreambot_examples::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dreambot_examples::AddTwoInts >::value();
  }
  static const char* value(const ::dreambot_examples::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dreambot_examples::AddTwoIntsRequest> should match
// service_traits::DataType< ::dreambot_examples::AddTwoInts >
template<>
struct DataType< ::dreambot_examples::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::dreambot_examples::AddTwoInts >::value();
  }
  static const char* value(const ::dreambot_examples::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dreambot_examples::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::dreambot_examples::AddTwoInts >
template<>
struct MD5Sum< ::dreambot_examples::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dreambot_examples::AddTwoInts >::value();
  }
  static const char* value(const ::dreambot_examples::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dreambot_examples::AddTwoIntsResponse> should match
// service_traits::DataType< ::dreambot_examples::AddTwoInts >
template<>
struct DataType< ::dreambot_examples::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::dreambot_examples::AddTwoInts >::value();
  }
  static const char* value(const ::dreambot_examples::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DREAMBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H
