// Generated by gencpp from file dreambot_examples/GetTransform.msg
// DO NOT EDIT!


#ifndef DREAMBOT_EXAMPLES_MESSAGE_GETTRANSFORM_H
#define DREAMBOT_EXAMPLES_MESSAGE_GETTRANSFORM_H

#include <ros/service_traits.h>


#include <dreambot_examples/GetTransformRequest.h>
#include <dreambot_examples/GetTransformResponse.h>


namespace dreambot_examples
{

struct GetTransform
{

typedef GetTransformRequest Request;
typedef GetTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTransform
} // namespace dreambot_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dreambot_examples::GetTransform > {
  static const char* value()
  {
    return "d44d0066649a82d7be9dc68623df55fc";
  }

  static const char* value(const ::dreambot_examples::GetTransform&) { return value(); }
};

template<>
struct DataType< ::dreambot_examples::GetTransform > {
  static const char* value()
  {
    return "dreambot_examples/GetTransform";
  }

  static const char* value(const ::dreambot_examples::GetTransform&) { return value(); }
};


// service_traits::MD5Sum< ::dreambot_examples::GetTransformRequest> should match
// service_traits::MD5Sum< ::dreambot_examples::GetTransform >
template<>
struct MD5Sum< ::dreambot_examples::GetTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dreambot_examples::GetTransform >::value();
  }
  static const char* value(const ::dreambot_examples::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dreambot_examples::GetTransformRequest> should match
// service_traits::DataType< ::dreambot_examples::GetTransform >
template<>
struct DataType< ::dreambot_examples::GetTransformRequest>
{
  static const char* value()
  {
    return DataType< ::dreambot_examples::GetTransform >::value();
  }
  static const char* value(const ::dreambot_examples::GetTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dreambot_examples::GetTransformResponse> should match
// service_traits::MD5Sum< ::dreambot_examples::GetTransform >
template<>
struct MD5Sum< ::dreambot_examples::GetTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dreambot_examples::GetTransform >::value();
  }
  static const char* value(const ::dreambot_examples::GetTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dreambot_examples::GetTransformResponse> should match
// service_traits::DataType< ::dreambot_examples::GetTransform >
template<>
struct DataType< ::dreambot_examples::GetTransformResponse>
{
  static const char* value()
  {
    return DataType< ::dreambot_examples::GetTransform >::value();
  }
  static const char* value(const ::dreambot_examples::GetTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DREAMBOT_EXAMPLES_MESSAGE_GETTRANSFORM_H
